function(wp_check_compiler)
  if(MSVC)
    set(WP_PLATFORM "win32" PARENT_SCOPE)
    if(MSVC_VERSION GREATER_EQUAL "1911")
      add_compile_options("/std:c++17")
    endif()
  else()
    include(CheckCXXCompilerFlag)
    CHECK_CXX_COMPILER_FLAG("-std=c++17" COMPILER_SUPPORTS_CXX17)
    if(COMPILER_SUPPORTS_CXX17)
      message("C++ standard: c++17")
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17" PARENT_SCOPE)
    else()
      CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
      if(COMPILER_SUPPORTS_CXX11)
        message("C++ standard: c++11")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11" PARENT_SCOPE)
      else()
        message(WARNING "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support.")
      endif()
    endif()

    if(CMAKE_CXX_COMPILER MATCHES ".+/emscripten/.+")
      set(CMAKE_CXX_COMPILER_ID "Emscripten" PARENT_SCOPE)
      set(WP_PLATFORM "html5" PARENT_SCOPE)
    elseif(APPLE)
      set(WP_PLATFORM "osx" PARENT_SCOPE)
    endif()
  endif()

  message("CMAKE_CXX_COMPILER: ${CMAKE_CXX_COMPILER}")
  message("CMAKE_CXX_COMPILER_ID: ${CMAKE_CXX_COMPILER_ID}")
  message("CMAKE_CXX_COMPILER_VERSION : ${CMAKE_CXX_COMPILER_VERSION}")
endfunction()
